dist: xenial
sudo: required
language: node_js
node_js: lts/*
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_829e1da235e2_key -iv $encrypted_829e1da235e2_iv
    -in config/deploy.gpg.enc -out config/deploy.gpg -d
  - ./scripts/decrypt.sh
install:
  - yarn
script:
  - yarn test
